const ASSESSMENT_TYPE = { 
    QUIZ: "QUIZ",
    ASSIGNMENT: "ASSIGNMENT",
    QUESTION_PAPER: "QUESTION-PAPER"
} as const;

const ASSESSMENT_DIFFICULTIES = {
    EASY: "EASY",
    MEDIUM: "MEDIUM",
    HARD: "HARD",
    MIXED: "MIXED"
} as const;

const QUESTION_TYPES = {
    MCQ: "MCQ",
    TRUE_FALSE: "TRUE-FALSE",
    SHORT_ANSWER: "SHORT-ANSWER",
    LONG_ANSWER: "LONG-ANSWER",
    CASE_STUDY: "CASE-STUDY"
} as const;

export { ASSESSMENT_DIFFICULTIES, QUESTION_TYPES, ASSESSMENT_TYPE };

